stages:
  - build
  - push
  - clean

build:
  tags:
    - shell
  stage: build
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
  only:
    - master
    - tags

push_ref:
  tags:
    - shell
  stage: push
  script:
    - echo "Login to docker registry"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - echo "Push container"
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - master

push_version:
  tags:
    - shell
  stage: push
  script:
    - echo "Login to docker registry"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - echo "Tag version ${CI_BUILD_TAG}"
    - docker tag ${CI_REGISTRY_IMAGE}:latest ${CI_REGISTRY_IMAGE}:$CI_BUILD_TAG
    - docker tag ${CI_REGISTRY_IMAGE}:latest ${CI_REGISTRY_IMAGE}:release
    - echo "Push container"
    - docker push ${CI_REGISTRY_IMAGE}:$CI_BUILD_TAG
    - docker push ${CI_REGISTRY_IMAGE}:release
  only:
    - tags

clean:
  tags:
    - shell
  stage: clean
  script:
    - docker rmi ${CI_REGISTRY_IMAGE}:latest
  only:
    - master
    - tags
