version: "2"

volumes:
  chain:
    driver: "local"

services:
  ethereum:
    image: eiabea/ethereum-testnode:1.6.5
    ports:
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:30303:30303"
    volumes:
      - "chain:/root"
    environment:
      TESTNODE_RPC_PORT: "8545"
      TESTNODE_RPC_ADDRESS: "0.0.0.0"
      TESTNODE_RPC_API: "personal,eth,net,web3"
      TESTNODE_IDENTITY: "Testnode"
      TESTNODE_VERBOSITY: "5"
      TESTNODE_MINING: "true"
      TESTNODE_MINING_THREADS: "1"